# This file configures the Dart analyzer for this project.
# See https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

# Additional rules for stricter analysis
linter:
  rules:
    - avoid_empty_else
    - avoid_relative_import_paths
    - avoid_returning_null_for_future
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - invariant_booleans
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks

analyzer:
  exclude: [build/**]
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
