#!/bin/bash

# Auto-Build Environment Setup
# Realistic GUI Test Suite for Flutter Sample App
# Generated by Planner Agent

set -e

echo "========================================"
echo "Realistic GUI Test Suite Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Project root
PROJECT_ROOT="E:/dev/FlutterReflect"
cd "$PROJECT_ROOT"

echo ""
echo "${BLUE}Project Root:${NC} $PROJECT_ROOT"
echo ""

# Function to check if port is in use
check_port() {
    local port=$1
    if netstat -an | grep -q ":$port.*LISTEN" 2>/dev/null; then
        return 0
    else
        return 1
    fi
}

# Function to wait for service
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -n "${YELLOW}Waiting for $name on port $port...${NC} "
    while ! check_port $port; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo ""
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
        echo -n "."
    done
    echo ""
    echo -e "${GREEN}$name is ready${NC}"
}

# ============================================
# CHECK PREREQUISITES
# ============================================

echo -e "${BLUE}Checking prerequisites...${NC}"

# Check if flutter_reflect.exe exists
if [ ! -f "build/Debug/flutter_reflect.exe" ]; then
    echo -e "${RED}ERROR: flutter_reflect.exe not found${NC}"
    echo "Please build the project first:"
    echo "  cmake --build build --config Debug"
    exit 1
fi
echo -e "${GREEN}✓ flutter_reflect.exe found${NC}"

# Check if Python is available
if ! command -v python &> /dev/null; then
    echo -e "${RED}ERROR: Python not found${NC}"
    echo "Please install Python 3.7+ to run tests"
    exit 1
fi
echo -e "${GREEN}✓ Python found${NC}"

# ============================================
# CHECK FLUTTER APP STATUS
# ============================================

echo ""
echo -e "${BLUE}Checking Flutter Sample App...${NC}"

if check_port 8181; then
    echo -e "${GREEN}✓ Flutter app is already running on port 8181${NC}"
else
    echo -e "${YELLOW}⚠ Flutter app is not running${NC}"
    echo ""
    echo "Please start the Flutter sample app in a separate terminal:"
    echo ""
    echo "  cd examples/flutter_sample_app"
    echo "  flutter run -d windows --vm-service-port=8181 --disable-service-auth-codes"
    echo ""
    echo "Waiting for you to start the app..."
    echo ""

    # Wait for user to start the app
    wait_for_service 8181 "Flutter Sample App"
    if [ $? -ne 0 ]; then
        echo -e "${RED}Failed to detect Flutter app${NC}"
        exit 1
    fi
fi

# ============================================
# DISPLAY INSTRUCTIONS
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services Status:"
echo -e "  ${GREEN}✓${NC} FlutterReflect Server: ${BLUE}build/Debug/flutter_reflect.exe${NC}"
echo -e "  ${GREEN}✓${NC} Flutter Sample App:   ${BLUE}Running on port 8181${NC}"
echo -e "  ${GREEN}✓${NC} Python:               ${BLUE}Available${NC}"
echo ""
echo "========================================"
echo "Running Tests"
echo "========================================"
echo ""
echo "To run the realistic GUI test suite:"
echo ""
echo "  ${YELLOW}python test_realistic_gui_suite.py${NC}"
echo ""
echo "This will:"
echo "  • Connect to Flutter app via VM Service (ws://127.0.0.1:8181/ws)"
echo "  • Initialize app and capture baseline state"
echo "  • Test ALL UI components on Home screen (input, buttons, checkboxes, delete)"
echo "  • Test ALL UI components on Stats screen (navigation, search, filters)"
echo "  • Verify each interaction occurred successfully"
echo "  • Detect and report UI state changes"
echo "  • Generate comprehensive test report"
echo ""
echo "Test output will be saved to: ${BLUE}docs/realistic_test_report.md${NC}"
echo ""
echo "========================================"
echo ""
